name: Quality Check & PR to Master

on:
  push:
    branches:
      - dev

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Set up Rust
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11' # You can change this to your preferred version
  #         cache: 'pip'

      # - name: Install Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #     pip install pytest # Ensures pytest is available even if not in requirements.txt

      # - name: Create .env file
      #   run: |

      # - name: Run Tests
      #   run: |
      #     mkdir logs
      #     pytest -s

  create_pull_request:
      runs-on: ubuntu-latest
      needs: test  # This creates the dependency link
      if: github.actor == 'brianobot'
      permissions:
        contents: write
        pull-requests: write
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Create Pull Request
          run: |
            # Check if a PR already exists from dev to master
            PR_EXISTS=$(gh pr list --head dev --base master --state open --json number -q '.[0].number')

            if [ -z "$PR_EXISTS" ]; then
              echo "No open PR found. Creating a new one..."
              gh pr create \
                --head dev \
                --base master \
                --title "Auto-PR: Dev to Master" \
                --body "Automated PR triggered by push from ${{ github.actor }}" \
                --assignee "${{ github.actor }}"
            else
              echo "PR already exists: #$PR_EXISTS. Skipping creation."
            fi
